config/routes.rb
Notebook::Application.routes.draw do

  root "notes#index"

  get '/notes', controller: 'notes', action: 'index', as: 'notes'

  post '/notes', controller: 'notes', action: 'create'

  get '/notes/:id/edit', controller: 'notes', action: 'edit', as: 'edit_note'
  patch '/notes/:id', controller: 'notes', action: 'update'

  delete '/notes/:id', controller: 'notes', action: 'destroy', as: 'note'

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
  end

  def show
    @note = Note.find_by(id: params[:id])
  end

  def new
  end

  def create
    @note = Note.new
    @note.content = params[:note][:content]

    if @note.save
      redirect_to notes_url, notice: "Note created successfully."
    else
      render 'new'
    end
  end

  def edit
    @note = Note.find_by(id: params[:id])
  end

  def update
    @note = Note.find_by(id: params[:id])
    @note.content = params[:content]

    if @note.save
      redirect_to notes_url, notice: "Note updated successfully."
    else
      render 'edit'
    end
  end

  def destroy
    @note = Note.find_by(id: params[:id])
    @note.destroy

    redirect_to notes_url, notice: "Note deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">

  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container" class="notepad">
    <header>
      <h1>
        <%= link_to image_tag('bulb.jpg', :size => '75x100'), root_url %>
        <%= link_to 'Aha! Notebook', root_url %>
      </h1>
    </header>
    <section>
      <%= yield %>
    </section>
  </div>
</body>
</html>

app/views/notes/edit.html.erb
<h1>Editing Note #<%= @note.id %></h1>

<%= form_tag(note_url(@note), method: 'patch') do %>
    <%= label_tag :content %><br />
    <%= text_field_tag :content, @note.content %>
    <%= submit_tag "Update Note" %>
<% end %>

app/views/notes/index.html.erb
<ul>
  <% @notes.each do |note| %>
  <li>
    <%= note.content %>
    <div>
      <%= link_to edit_note_url(note) do %>
        <i class="fa fa-edit"></i>
      <% end %>

      <%= link_to '<i class="fa fa-trash-o"></i>'.html_safe, note_url(note), method: 'delete' %>
    </div>
  </li>
  <% end %>
  <li>
    <%= form_for Note.new do |f| %>
      <%= f.text_field :content, placeholder: 'Add a new aha! here', size: 50, autofocus: true %>
    <% end %>
  </li>

</ul>

app/views/notes/show.html.erb
<h1>Note #<%= @note.id %></h1>

<dl>
  <dt>Content</dt>
  <dd><%= @note.content %></dd>

</dl>